apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express-roll
  labels:
    somelb: some
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          name: express
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
  minReadySeconds: 30
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 15s}